var json = [
        {"id": 0, "name": "如何学D3", "parent": ""},
        {"id": 1, "name": "预备知识", "parent": "0"},
        {"id": 2, "name": "安装", "parent": "0"},
        {"id": 3, "name": "入门", "parent": "0"},
        {"id": 4, "name": "进阶", "parent": "0"},
        {"id": 5, "name": "HTML&CSS", "parent": "1"},
        {"id": 6, "name": "JavaScript", "parent": "1"},
        {"id": 7, "name": "DOM", "parent": "1"},
        {"id": 8, "name": "SVG", "parent": "1"},
        {"id": 9, "name": "记事本软件", "parent": "2"},
        {"id": 10, "name": "服务器软件", "parent": "2"},
        {"id": 11, "name": "下载D3.js", "parent": "2"},
        {"id": 12, "name": "选择集", "parent": "3"},
        {"id": 13, "name": "绑定数据", "parent": "3"},
        {"id": 14, "name": "添加删除元素", "parent": "3"},
        {"id": 15, "name": "简单图形", "parent": "3"},
        {"id": 16, "name": "比例尺", "parent": "3"},
        {"id": 17, "name": "生成器", "parent": "3"},
        {"id": 18, "name": "过度", "parent": "3"},
        {"id": 19, "name": "布局的应用", "parent": "4"},
        {"id": 20, "name": "地图", "parent": "4"},
        {"id": 21, "name": "Notepad++", "parent": "9"},
        {"id": 22, "name": "EditPlus", "parent": "9"},
        {"id": 23, "name": "Sublime Text", "parent": "9"},
        {"id": 24, "name": "Apache Http Server", "parent": "10"},
        {"id": 25, "name": "Tomcat", "parent": "10"},
        {"id": 26, "name": "select", "parent": "12"},
        {"id": 27, "name": "selectAll", "parent": "12"},
        {"id": 28, "name": "dataum", "parent": "13"},
        {"id": 29, "name": "data", "parent": "13"},
        {"id": 30, "name": "柱形图", "parent": "15"},
        {"id": 31, "name": "折线图", "parent": "15"},
        {"id": 32, "name": "散点图", "parent": "15"},
        {"id": 33, "name": "饼状图", "parent": "19"},
        {"id": 34, "name": "树状图", "parent": "19"},
        {"id": 35, "name": "矩阵树图", "parent": "19"}
];