var json = {
    "nodes": [
        {"id": 0, "name": "如何学D3"},
        {"id": 1, "name": "预备知识"},
        {"id": 2, "name": "安装"},
        {"id": 3, "name": "入门"},
        {"id": 4, "name": "进阶"},
        {"id": 5, "name": "HTML&CSS"},
        {"id": 6, "name": "JavaScript"},
        {"id": 7, "name": "DOM"},
        {"id": 8, "name": "SVG"},
        {"id": 9, "name": "记事本软件"},
        {"id": 10, "name": "服务器软件"},
        {"id": 11, "name": "下载D3.js"},
        {"id": 12, "name": "选择集"},
        {"id": 13, "name": "绑定数据"},
        {"id": 14, "name": "添加删除元素"},
        {"id": 15, "name": "简单图形"},
        {"id": 16, "name": "比例尺"},
        {"id": 17, "name": "生成器"},
        {"id": 18, "name": "过度"},
        {"id": 19, "name": "布局的应用"},
        {"id": 20, "name": "地图"},
        {"id": 21, "name": "Notepad++"},
        {"id": 22, "name": "EditPlus"},
        {"id": 23, "name": "Sublime Text"},
        {"id": 24, "name": "Apache Http Server"},
        {"id": 25, "name": "Tomcat"},
        {"id": 26, "name": "select"},
        {"id": 27, "name": "selectAll"},
        {"id": 28, "name": "dataum"},
        {"id": 29, "name": "data"},
        {"id": 30, "name": "柱形图"},
        {"id": 31, "name": "折线图"},
        {"id": 32, "name": "散点图"},
        {"id": 33, "name": "饼状图"},
        {"id": 34, "name": "树状图"},
        {"id": 35, "name": "矩阵树图"}
    ],
    "links": [
        {"source": 0, "target": 1},
        {"source": 0, "target": 2},
        {"source": 0, "target": 3},
        {"source": 0, "target": 4},
        {"source": 1, "target": 5},
        {"source": 1, "target": 6},
        {"source": 1, "target": 7},
        {"source": 1, "target": 8},
        {"source": 2, "target": 9},
        {"source": 2, "target": 10},
        {"source": 2, "target": 11},
        {"source": 3, "target": 12},
        {"source": 3, "target": 13},
        {"source": 3, "target": 14},
        {"source": 3, "target": 15},
        {"source": 3, "target": 16},
        {"source": 3, "target": 17},
        {"source": 3, "target": 18},
        {"source": 4, "target": 19},
        {"source": 3, "target": 20},
        {"source": 9, "target": 21},
        {"source": 9, "target": 22},
        {"source": 9, "target": 23},
        {"source": 10, "target": 24},
        {"source": 10, "target": 25},
        {"source": 12, "target": 26},
        {"source": 12, "target": 27},
        {"source": 13, "target": 28},
        {"source": 13, "target": 29},
        {"source": 15, "target": 30},
        {"source": 15, "target": 31},
        {"source": 15, "target": 32},
        {"source": 19, "target": 33},
        {"source": 10, "target": 34},
        {"source": 10, "target": 35}
    ]
};